title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- .github
- public
- scripts
- vendor
- assets
- logs
- templates
ext:
- go
enablerun: true
action:
  before:
  - go generate internal/assets/conf/conf.go
  after:
  - echo "zzz end"
  exit:
  - echo "exit"
link: https://github.com/midoks/zzz
