title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- .github
- public
- scripts
- vendor
- assets
- logs
- templates
ext:
- go
enablerun: false
action:
  before:
  - go generate internal/assets/conf/conf.go
  - ps -ef|grep 'freeproxy web'| grep -v grep | awk '{print $2}' | xargs kill -9
  after:
  - ./freeproxy web &
  exit:
  - ps -ef|grep 'freeproxy web'| grep -v grep | awk '{print $2}' | xargs kill -9
link: https://github.com/midoks/zzz
